### ISSUE TITLE
TS Class extends value #<Object> is not a constructor of null

### ISSUE THREAD

**Issue by juliancoleman** [scoutforpets/objection-password#14]
I don't think this is a bug with `objection-password`, however, this issue has me stumped. When attempting to create a `User` Mode, I get the following error:

```ts
// tslint:disable:variable-name
import * as Base from "./base";

const Password = require("objection-password")();

export default class User extends Password(Base) {
  static tableName() {
    return "users";
  }

  public readonly id: number;
  public firstName: string;
  public lastName: string;
}

////////

/path/to/github/ts-hapi-api/models/user.ts:9
export default class User extends Password(Base) {
                                  ^
TypeError: Class extends value #<Object> is not a constructor or null
    at /home/julian/Documents/github/ts-hapi-api/node_modules/objection-password/index.js:20:5
    at Object.<anonymous> (/home/julian/Documents/github/ts-hapi-api/models/user.ts:9:35)
```

And if I try to just

```ts
import * as Password from "objection-password";
```

Then I get an error that `[ts] Property 'query' does not exist on typeof 'User'`

**Comment by juliancoleman** [comment]
It appears that this is caused by a circular dependency, but I'm not sure from where

**Comment by juliancoleman** [comment]
And here's my `Base` `Model`

```ts
import { renameKeysWith } from "ramda-adjunct";
import { underscored, camelize } from "underscore.string";
import { Model } from "objection";

export default class Base extends Model {
  $formatDatabaseJson(json) {
    const formattedJson = super.$formatDatabaseJson(json);

    return renameKeysWith(underscored, formattedJson);
  }

  $parseDatabaseJson(json) {
    return super.$parseDatabaseJson(renameKeysWith(camelize, json));
  }
}
```

**Comment by juliancoleman** [comment]
Okay, it was caused by `import * as Base from "./base"` instead of `import Base from "./base"`

**Comment by rahulmogar** [comment]
i used **import Base from ' ./base.js'**   and its working, thanks
